### ISSUE TITLE
Presentation vs. Semantic XML

### ISSUE THREAD

**Issue by strogonoff** [metanorma/firelight#9]
Currently apparently this Firelight thing is set up to read Semantic XML (`*.xml`). That was a stupid design decision, taken by people who did not talk to me and did not know what they were doing. It should be consuming Presentation XML (`*.presentation.xml`), which resolves numbering, does i18n, orders clauses, resolves passthrough blocks, and any number of other things. The entire reason Presentation XML exists is so that Alex D and I did not have to redo this work independently: any attempt by Firelight to redo the same work from scratch needs to be kerb-stomped.

As it turns out, the Presentation XML embeds the Semantic XML at the beginning anyway (`semantic_` prefixed to all elements and anchors with equivalents in the Presentation XML.)

There is an action coming up on me to create and document the Presentation XML schema, so you know what its value-add is.

_Originally posted by @opoudjis in https://github.com/metanorma/firelight/issues/8#issuecomment-2319518207_

**Comment by strogonoff** [comment]
In Firelight there’s great amounts of hard-coded logic like in this example from formatting nav:

```
if (standard === 'ogc-standard' && hasIndex && title === 'Introduction') {
  title = `${count} ${returnData.title}`;
}
```

@opoudjis would you say, off the top of your head…

- Using presentation XML means *none* of such logic would be necessary, it’ll be straightforward universal rendering for all flavours
- Using presentation XML would *reduce* the amount of such logic
- It’s orthogonal

**Comment by ronaldtse** [comment]
@opoudjis is conveniently ignoring the fact that the new “presentation XML combined with semantic XML” format didn’t exist when Firelight was implemented. 

@strogonoff the answer is a combination of the three, but mostly orthogonal. The Presentation XML content will provide some business logic, such as clause numbers, title formats, etc. But other important things like: terms and definitions, bibliographic content, will use content from the semantic portion.

**Comment by ronaldtse** [comment]
@strogonoff Presentation XML will not help with the code you quoted. The current implementation is a rough draft, but just consider that in the future different organizations will use differentiated components to render things.

**Comment by opoudjis** [comment]
Anton, spend some time talking to Alex D about how rendering works. Or me. And look at the metanorma-*/lib/isodoc/html*rb and isodoc/lib/function, isodoc/lib/html_convert code, to get a sense of what actual Metanorma is doing with HTML.

I know nothing about Firelight, and I hope that continues to be the case, but PDF uses different stylesheets for different flavours, just as Metanorma uses different gems for different SDOs. The PDF stylesheets inherit from a different core, and so do the HTML renderers, but there are going to be rendering decisions that are specific to a flavour, and that will require either a different rendering module, or logic. If Firelight is using logic... that is simply not going to scale.

Presentation XML adds text (i18n, numbering, cross-references). Presentation XML changes markup (notably recommendations turned into tables). And Presentation XML is shared between PDF, HTML, and DOC: it is not going to do styling specific to an output format. There will be no CSS styles chosen inside of Presentation XML: that's the HTML renderer's business. And some of that styling is going to be flavour-specific. Have a look at some of the metanorma flavours' lib/isodoc/*/html_convert.rb code to see instances; they are usually not huge amounts of code, but they are non-zero.

The Presentation XML was not in there from the beginning, which means there is some logic in PDF and HTML rendering that still should be done at Presentation XML, and I occasionally refactor some back out. But by now, there is not a lot.

**Comment by opoudjis** [comment]
In the specific instance you give, though, @strogonoff , if it's what I think it is,

then  this is clause numbering of titles, with conditions on whether Introductions get clause numbering or not. That is EXPLICITLY addressed in Presentation XML, and Firelight has chosen to ignore the fact that someone who knows a lot better what the rendering requirements are for each flavour has already implemented this behaviour, and is choosing to reimplementing it from scratch, badly, without once speaking to me.

Don't continue that. Presentation XML resolves clause numbering. Kill with extreme prejudice any code in Firelight that is reimplementing clause numbering.

**Comment by opoudjis** [comment]
The real way forward here is for me to document the changes in Presentation XML as a schema (and also what changes in Presentation XML that does not change the schema). A big task, but a necessary one.

**Comment by strogonoff** [comment]
> That is EXPLICITLY addressed in Presentation XML

Got it. So, at least some of that logic would go away (so that’s somewhat good), but not all of it (so Firelight’ll have to implement pluggable per-standard logic of this sort anyway).

**Comment by ronaldtse** [comment]
Only **some** of that logic goes away. There is a misunderstanding that Presentation XML does everything. No it does not.

Firelight is supposed to be an APP, not a static document site.

**Comment by ronaldtse** [comment]
@strogonoff @opoudjis please see this diagram on where Firelight is supposed to work -- at the Semantic level. It can use **some** things from Presentation XML.

The positioning of Firelight and PDF is **very very very different**. PDF is a read-only format. Firelight is an **APP**.

Also, each flavor will have a separate implementation of Firelight while **sharing a common core**. For example, PDF Association will have their own JS layout elements to override defaults.

<img width="1559" alt="Screenshot 2024-08-30 at 8 03 48 PM" src="https://github.com/user-attachments/assets/4706e20e-81a6-4c6b-a76b-b41132d4f2e0">

**Comment by strogonoff** [comment]
@ronaldtse 

> There is a misunderstanding that Presentation XML does everything. No it does not. 

Not quite misunderstanding, I did not have a clear idea and that’s why I asked this question to determine which would be the more correct understanding.

> Firelight is supposed to be an APP, not a static document site.

Maybe we can dig in detail what that means, since I don’t exactly understand the meaning. I think some characteristics of a static document site are actually desirable, like for SEO purposes in case of PLATEAU and others.

**Comment by ronaldtse** [comment]
SEO is merely **one of the features** of a Metanorma standard. It is far from being the **purpose** of Metanorma. For SEO purposes, we can just generate plain static unstyled HTML.

**Comment by strogonoff** [comment]
It’s a good idea to separate rendering documents (which is what Firelight is now) and editing documents. If we combine them in a single GUI, we may shoot ourselves in the foot. I am totally on board that a GUI for editing Metanorma is called for, but right now while working on Firelight I don’t see it so that I’m working on *that* precisely…

**Comment by strogonoff** [comment]
If we are talking about rendering/viewing/browsing documents, a single-page dynamic app doesn’t seem (to me) to have obvious benefits compared to a static site. In fact, the line between the two is somewhat blurred nowadays with server-side components and all that, allowing to have both benefits of a static website (SEO, accessibility, etc.) while not having to wait for page loads as with traditional sites. 

I know what you mean though, we want the experience of reading/browsing *very large* documents to be convenient, and traditional static HTML sites doesn’t get us that.
